services:
  - type: web
    name: resume-analyzer-backend
    env: python
    pythonVersion: 3.9.18
    buildCommand: |
      apt-get update && apt-get install -y \
        libmupdf-dev \
        libjpeg-dev \
        zlib1g-dev \
        build-essential \
        python3-dev \
        swig \
        pkg-config \
        libfreetype6-dev \
        libpng-dev
      python -m pip install --upgrade pip
      pip install wheel setuptools
      CFLAGS="-I/usr/include/freetype2" pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*" 